# Generated by Django 2.2.15 on 2020-09-16 03:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slaves_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
